### ISSUE TITLE
Please add Cython to the list of dependencies.

### ISSUE THREAD

**Issue by Jigyasu** [hovren/crisp#10]

**Comment by hovren** [comment]
To which list should it be added?

In the source packages/releases (i.e. on PyPI) the Cython-generated C-files are included, and thus Cython is not needed for installation.
Therefore you only need Cython if you are cloning the repository from Github.
So, adding Cython to the `requires=` or `install_requires=` options in `setup()` is going to pull in Cython for *everyone* even though they don't need it, and I am hesistant to do so.
