### ISSUE TITLE
A bug in tracking.py

### ISSUE THREAD

**Issue by youruncleda** [hovren/crisp#11]
At line 208, I think "final_ok = np.intersect1d(ok_track, retracked_ok)" is wrong ,it should be "final_ok=ok_track[retracked_ok]". Because ok_track is forward_track and backward_track 's index, but retracked_ok is forward_first and backward_last 's index . They are not the same index. So they can't do the "intersect1d" operate. "retracked_ok" is "ok_track" 's index.

**Comment by hovren** [comment]
Thanks for finding this bug! I have committed a fix.
