### ISSUE TITLE
understanding

### ISSUE THREAD

**Issue by brunocannavina** [hovren/crisp#13]
I have several doubts, the first is how I calculate the matrix k,
the vector wc and omega,
readout is not 1/fps ¿why?
and finally where the stabilized video is exported (I can run the program perfectly but I do not see results)
I am using a gopro hero5.

**Comment by hovren** [comment]
K, wc and omega are camera parameters that you need to calibrate for. 
I have code for that here: https://github.com/hovren/atan_calib but I give no support for this.

The readout is the time to read out the frame, and can be at most 1/fps. Lower values are better. Please see the paper for details on rolling shutter.
