### ISSUE TITLE
stability  of  parameter  estimation

### ISSUE THREAD

**Issue by mppcasc** [hovren/crisp#16]
Hi, I used the calibration toolbox to calibrate the data given by the paper, and the result was different every time.
In the experimental section of the paper, figure 4 shows the error relative to the set of reference parameters. The frequency error is within +/ -0.2, and the time offset error is between -0.008 and 0004. The results obtained within this range can achieve a nicely  stabilised  video, but the results of my calibration each time exceed the above range, resulting in the use of calibrated parameters can not generate a good stabilised  video.

Here are some of the results I got(rotation.mp4):

Frequency(Hz)      -1.245274        0.7984233       -1.291282
Offset(s)               0.004855215    0.004855141    0.004858229

**Comment by hovren** [comment]
When we wrote the paper the method was very stable on that particular test sequence, so I have no idea what can be wrong now. My best guess would be that there has been some change in one of the libraries we use (scipy, OpenCV, ...) over the last 6 years since we published this code.
